// Code generated by MockGen. DO NOT EDIT.
// Source: upfile/internal/userfile (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -typed -package userfile -destination ./store_mock.go . Store
//

// Package userfile is a generated GoMock package.
package userfile

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ReadFile mocks base method.
func (m *MockStore) ReadFile(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockStoreMockRecorder) ReadFile(ctx, path any) *MockStoreReadFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockStore)(nil).ReadFile), ctx, path)
	return &MockStoreReadFileCall{Call: call}
}

// MockStoreReadFileCall wrap *gomock.Call
type MockStoreReadFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreReadFileCall) Return(arg0 string, arg1 error) *MockStoreReadFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreReadFileCall) Do(f func(context.Context, string) (string, error)) *MockStoreReadFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreReadFileCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockStoreReadFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
