version: "2"
linters:
  default: all
  disable:
    - cyclop
    - dupword
    - funlen
    - nlreturn
    - gochecknoglobals
    - gocognit
    - varnamelen
    - gocyclo
    - godot
    - godox
    - maintidx
    - nestif
    - nolintlint
    - recvcheck
    - mnd
    - wsl
  settings:
    govet:
      # Enable all analyzers.
      # Default: false
      enable-all: true
      disable:
        - fieldalignment # too strict
      settings:
        shadow:
          # Whether to be strict about shadowing; can be noisy.
          # Default: false
          strict: true
    exhaustive:
      # Presence of "default" case in switch statements satisfies exhaustiveness,
      # even if all enum members are not listed.
      # Default: false
      default-signifies-exhaustive: true
      check:
        - switch
        - map
    gosec:
      excludes:
    #     - G104
        - G204
    #     - G301
        - G304
    revive:
      rules:
        - name: blank-imports
          disabled: true
    nakedret:
      # Make an issue if func has more lines of code than this setting, and it has naked returns.
      # Default: 30
      max-func-lines: 0
    forbidigo:
      forbid:
        - pattern: os.IsNotExist
          msg: "use errors.Is(err, os.ErrNotExist) instead of os.IsNotExist"
        - pattern: os.IsExist
          msg: "use errors.Is(err, os.ErrExist) instead of os.IsExist"
    wrapcheck:
      ignore-package-globs:
        - os
    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      # Default: false
      check-type-assertions: true
    depguard:
      rules:
        all:
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: reflect
              desc: Please don't use reflect package
            - pkg: io/ioutil
              desc: io/ioutil package has been deprecated
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead, see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid instead, satori's package is not maintained
            - pkg: github.com/gofrs/uuid$
              desc: Use github.com/gofrs/uuid/v5 or later, it was not a go module before v5
        "non-main files":
          files:
            - "!**/main.go"
          deny:
            - pkg: log$
              desc: Use log/slog instead, see https://go.dev/blog/slog
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          xml: camel
          bson: camel
          avro: snake
          mapstructure: kebab
    exhaustruct:
      exclude:
        - ^net/http.Client$
        - ^net/http.Cookie$
        - ^net/http.Request$
        - ^net/http.Response$
        - ^net/http.Server$
        - ^net/http.Transport$
        - ^net/url.URL$
        - ^log/slog.HandlerOptions$
        - ^os/exec.Cmd$
        - ^reflect.StructField$
        - ^github.com/Shopify/sarama.Config$
        - ^github.com/Shopify/sarama.ProducerMessage$
        - ^github.com/mitchellh/mapstructure.DecoderConfig$
        - ^github.com/prometheus/client_golang/.+Opts$
        - ^github.com/spf13/cobra.Command$
        - ^github.com/spf13/cobra.CompletionOptions$
        - ^github.com/ivanpirog/coloredcobra.Config$
        - ^github.com/stretchr/testify/mock.Mock$
        - ^github.com/testcontainers/testcontainers-go.+Request$
        - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
        - ^golang.org/x/tools/go/analysis.Analyzer$
        - ^google.golang.org/protobuf/.+Options$
        - ^gopkg.in/yaml.v3.Node$
        - ^github.com/golang-jwt/jwt.v5.RegisteredClaims$
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
      - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
        linters:
          - govet
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - err113
          - exhaustruct
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
formatters:
  enable:
    - gofmt
    - goimports
