# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: upfile
before:
  hooks:
    - go mod tidy

builds:
  - binary: upfile
    main: ./cmd/upfile/
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - "^docs:"
#       - "^test:"
aurs:
  - name: upfile-bin
    description: A CLI tool to manage and sync shared configuration files across projects.
    skip_upload: false
    homepage: https://github.com/skewb1k/upfile
    maintainers:
      - "skewb1k <skewb1kunix@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/upfile-bin.git"
    package: |-
      # bin
      install -Dm755 "./upfile" "${pkgdir}/usr/bin/upfile"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      "${pkgdir}/usr/bin/upfile" completion bash > "${pkgdir}/usr/share/bash-completion/completions/upfile"
      "${pkgdir}/usr/bin/upfile" completion zsh > "${pkgdir}/usr/share/zsh/site-functions/_upfile"
      "${pkgdir}/usr/bin/upfile" completion fish > "${pkgdir}/usr/share/fish/vendor_completions.d/upfile.fish"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/upfile/LICENSE"
brews:
  - repository:
      owner: skewb1k
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: skewb1k
      email: skewb1kunix@gmail.com
    homepage: github.com/skewb1k/upfile
    description: A CLI tool to manage and sync shared configuration files across projects.
    install: |-
      bin.install "upfile"
      bash_output = Utils.safe_popen_read("#{bin}/upfile", "completion", "bash")
      (bash_completion/"upfile").write bash_output
      zsh_output = Utils.safe_popen_read("#{bin}/upfile", "completion", "zsh")
      (zsh_completion/"_upfile").write zsh_output
      fish_output = Utils.safe_popen_read("#{bin}/upfile", "completion", "fish")
      (fish_completion/"upfile.fish").write fish_output
